### ISSUE TITLE
incompat with legendary tooltips

### ISSUE THREAD

**Issue by thvless** [Xylonity/Knight-Quest#1]
using LegendaryTooltips-1.20.1-forge-1.4.5 and knightquest-1.3.0 on 1.20.1 forge 47.2.18

when using [Knightquest](https://www.curseforge.com/minecraft/mc-mods/knight-quest-reforged) in conjunction with [legendary tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)' render item model feature that normally shows the 3d model of the armor, some helmets from knightquest will render both the 2d item and the 3d item on top of it (and outside the frame it should be in)

issue:
![image_77](https://github.com/user-attachments/assets/a5ce2afb-7b2f-4a1f-81d3-634c87845f4b)

expected behavior: 
![image](https://github.com/user-attachments/assets/59306d20-cb7f-4eb0-a935-652d8c5c9488)

logs
[latest.log](https://github.com/user-attachments/files/16784387/latest.log)
[debug.log](https://github.com/user-attachments/files/16784391/debug.log)

this issue was also reported on the [legendary tooltips github](https://github.com/AHilyard/LegendaryTooltips/issues/152)

**Comment by thvless** [comment]
tested again with latest knightquest 1.5.3 and issue is still present

**Comment by Xylonity** [comment]
Incompatibility issue between Legendary Tooltips/Iceberg and Geckolib, this is not a direct problem with this mod, so I'm closing the issue.
