### ISSUE TITLE
Incompatibility Knight Quest 1.20.1 Fabric

### ISSUE THREAD

**Issue by worm-in-concrete** [Xylonity/Knight-Quest#3]
https://mclo.gs/JyDJOhm
Crash when loading Minecraft.

knightquest-fabric-1.20.1-1.7.2
spritearrows-fabric-1.20-1.0.4
MC Fabric 1.20.1

**Comment by Xylonity** [comment]
Bug between spritearrows and geckolib, it looks like knightquest is the trigger. The creator of that mod seems to be active, did you already report this issue in their git repo?
