### ISSUE TITLE
[Crash-Fabric 1.21.1] While fighting ratman

### ISSUE THREAD

**Issue by Aesthir** [Xylonity/Knight-Quest#4]
Unexpected crash took down the whole server. Here's the crash report: 
[crash-2024-11-09_04.56.18-server.txt](https://github.com/user-attachments/files/17687014/crash-2024-11-09_04.56.18-server.txt)

**Comment by Xylonity** [comment]
Try using 1.7.0, I archived the versions above

**Comment by Xylonity** [comment]
Fixed in the latest version
