### ISSUE TITLE
[Crash - Fabric 1.21.1] Broken great chalice

### ISSUE THREAD

**Issue by Aesthir** [Xylonity/Knight-Quest#5]
Client crashed when holding a great essence. I rebooted, entered the server again and right clicked with an ampty goblet, and it crashed the client again. Here's a [report](https://mclo.gs/DYMZnLo).

**Comment by Xylonity** [comment]
Make sure you're using the newest knightquest-1.7.1 build. I archived the past 1.7.1 version and uploaded another one under the same name (the one that's published right now)

**Comment by Aesthir** [comment]
Ohhh, nice! I see 1.7.2 is up now... tried it out, and it works as expected once again... thanks! :^)
