### ISSUE TITLE
[Enhancement] Enchantable weaponry that looks threatening

### ISSUE THREAD

**Issue by Aesthir** [Xylonity/Knight-Quest#7]
Two things with the weapons:

1. If the knightquest weapons are not enchantable then nobody will use them. When I place a khopesh on an enchanting table, there are no enchantments available. None show up in REI either, making it unenchantable. I'm not sure if this was intentional.
2. The models for the weapons look fine in the inventory, but when you wield a weapon or place one in the hand of an armor stand, it's about the size of a dagger. The nail glaive is supposed to be a polearm style weapon, and the khopesh is supposed to be claymore-sized, but both look like fancy daggers gripped by one hand. I'm not sure if that was intentional either.

**Comment by Xylonity** [comment]
Same comment as https://github.com/Xylonity/Knight-Quest/issues/5#issuecomment-2480234161

**Comment by Xylonity** [comment]
This is fixed as of 1.7.1 and above. To answer the second question, the weapon names include weapon-specific generic names (for example, nail_"glaive") so they use the default animations from better combat. 1.8.0 will come with some tweaks to the weapon system (including passive and active effects for most of them), so the existing names will be probably deprecated
